export const migrations = [
  `CREATE TABLE catalogue_owner (id TEXT PRIMARY KEY CHECK(id = 'owner'), identity TEXT NOT NULL UNIQUE)`,
  `CREATE TABLE recipes (user_id TEXT NOT NULL, project_id TEXT NOT NULL, id TEXT NOT NULL, revision INTEGER NOT NULL, hash TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(user_id, project_id, revision), UNIQUE(user_id, id, revision))`,
  `CREATE TABLE contexts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT NOT NULL, hash TEXT NOT NULL, expiry INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)))`,
  `CREATE TABLE builds (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, project_id TEXT NOT NULL, account_id TEXT NOT NULL, app TEXT NOT NULL, hash TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('queued','building','ready','failed','cancelled','reconciling')), vendor_ref TEXT NOT NULL, lease TEXT, data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(user_id,account_id,app,hash))`,
  `CREATE INDEX builds_queue ON builds(state,account_id)`,
  `CREATE INDEX builds_project ON builds(user_id,project_id,id)`,
  `CREATE UNIQUE INDEX builds_account_claim ON builds(account_id) WHERE state IN ('building','reconciling')`,
  `CREATE TABLE build_requests (user_id TEXT NOT NULL, key TEXT NOT NULL, payload_hash TEXT NOT NULL, build_id TEXT NOT NULL REFERENCES builds(id), PRIMARY KEY(user_id,key))`,
  `CREATE TABLE build_events (build_id TEXT NOT NULL REFERENCES builds(id), sequence INTEGER NOT NULL, kind TEXT NOT NULL, text TEXT NOT NULL, time INTEGER NOT NULL, bytes INTEGER NOT NULL, PRIMARY KEY(build_id,sequence))`,
  `CREATE TABLE images (build_id TEXT PRIMARY KEY REFERENCES builds(id), user_id TEXT NOT NULL, image_id TEXT NOT NULL, manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)), marked_at INTEGER, deleting INTEGER NOT NULL DEFAULT 0, deleted_at INTEGER)`,
  `CREATE TABLE project_images (user_id TEXT NOT NULL, project_id TEXT NOT NULL, usable_build_id TEXT REFERENCES builds(id), revision INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(user_id,project_id))`,
  `CREATE TABLE verifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, build_id TEXT NOT NULL REFERENCES builds(id), state TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)))`,
  `CREATE INDEX verifications_build ON verifications(user_id,build_id,state)`,
  `CREATE TABLE image_references (user_id TEXT NOT NULL, owner_kind TEXT NOT NULL, owner_id TEXT NOT NULL, build_id TEXT NOT NULL REFERENCES builds(id), PRIMARY KEY(user_id,owner_kind,owner_id,build_id))`,
  `CREATE INDEX image_references_build ON image_references(user_id,build_id)`,
  `CREATE TABLE context_uploads (context_id TEXT PRIMARY KEY REFERENCES contexts(id), token_hash TEXT NOT NULL, host_id TEXT NOT NULL)`,
  `CREATE TABLE context_chunks (context_id TEXT NOT NULL REFERENCES contexts(id), path TEXT NOT NULL, offset INTEGER NOT NULL, data BLOB NOT NULL, PRIMARY KEY(context_id,path,offset))`,
  `CREATE TABLE source_observations (user_id TEXT NOT NULL, project_id TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), checked_at INTEGER NOT NULL, PRIMARY KEY(user_id,project_id))`,
  `CREATE TABLE base_artifacts (hash TEXT PRIMARY KEY, metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)), data BLOB NOT NULL)`,
  `CREATE INDEX contexts_expiry ON contexts(user_id,expiry)`,
  `CREATE TABLE verification_requests (user_id TEXT NOT NULL, key TEXT NOT NULL, payload_hash TEXT NOT NULL, verification_id TEXT NOT NULL REFERENCES verifications(id), PRIMARY KEY(user_id,key))`,
  `UPDATE recipes SET data=json_remove(data, '$.setupScriptText')`,
];
